import React, { useState } from 'react';
import { useApp } from '../context/AppContext';
import {
  Target,
  Sparkles,
  BookOpen,
  Award,
  Clock,
  CheckCircle2,
  AlertCircle,
  ArrowRight,
  ShieldCheck,
  Flame,
  Brain,
} from 'lucide-react';
import { NIGERIAN_EXAMS_DATA } from '../data/curriculum';
import { ExamType } from '../types';

export const NigerianExamsView: React.FC = () => {
  const { currentUser, setCurrentUser, selectTopicAndLaunch, setCurrentView } = useApp();
  const [selectedExam, setSelectedExam] = useState<string>('JAMB');

  const activeExamData =
    NIGERIAN_EXAMS_DATA.find((e) => e.code === selectedExam) || NIGERIAN_EXAMS_DATA[2];

  const handleSetTargetExam = (examCode: string) => {
    setCurrentUser((prev) => ({ ...prev, targetExam: examCode as ExamType }));
  };

  return (
    <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 py-8 space-y-8">
      {/* Banner */}
      <div className="rounded-3xl bg-gradient-to-r from-emerald-800 via-teal-900 to-slate-900 text-white p-8 overflow-hidden relative shadow-xl">
        <div className="relative z-10 max-w-3xl space-y-4">
          <div className="inline-flex items-center gap-2 px-3 py-1 rounded-full bg-emerald-500/20 text-emerald-300 border border-emerald-400/30 text-xs font-bold uppercase tracking-wider">
            <Target className="w-3.5 h-3.5" />
            <span>Nigerian Curriculum & National Examination Center</span>
          </div>

          <h1 className="text-3xl sm:text-4xl font-extrabold tracking-tight">
            Master WAEC, NECO, JAMB & Common Entrance
          </h1>

          <p className="text-sm sm:text-base text-emerald-100 leading-relaxed">
            SmartTutor AI is calibrated to the official syllabi of Nigerian secondary and tertiary examinations.
            Train with timed CBT simulations, step-by-step theory working, and examiner marking guides.
          </p>

          <div className="flex flex-wrap items-center gap-3 pt-2">
            <button
              onClick={() => selectTopicAndLaunch('math', 'math-algebra', 'quiz')}
              className="px-5 py-2.5 rounded-xl bg-emerald-500 hover:bg-emerald-400 text-slate-950 font-bold text-xs shadow-md shadow-emerald-500/30 flex items-center gap-2 transition-all"
            >
              <span>Launch 40-Question Timed Mock CBT</span>
              <ArrowRight className="w-4 h-4" />
            </button>
            <button
              onClick={() => selectTopicAndLaunch('math', 'math-algebra', 'aitutor')}
              className="px-4 py-2.5 rounded-xl bg-white/10 hover:bg-white/20 text-white text-xs font-semibold border border-white/20 flex items-center gap-2 transition-all"
            >
              <Brain className="w-4 h-4" />
              <span>Ask AI About Exam Format</span>
            </button>
          </div>
        </div>
      </div>

      {/* Official Disclaimer Callout */}
      <div className="p-4 rounded-2xl bg-amber-50 dark:bg-amber-950/40 border border-amber-200 dark:border-amber-800 flex items-start gap-3 text-xs text-amber-800 dark:text-amber-300">
        <AlertCircle className="w-5 h-5 shrink-0 text-amber-600 dark:text-amber-400 mt-0.5" />
        <p className="leading-relaxed">
          <strong>Official Examination Disclaimer:</strong> SmartTutor AI provides simulated practice and tutorial explanations generated to mirror the style and requirements of official examination syllabi (WAEC, NECO, JAMB UTME, and NCEE). Practice questions are generated by AI for educational purposes and are not live or leaked official question papers.
        </p>
      </div>

      {/* Examination Selector Tabs */}
      <div className="grid grid-cols-2 sm:grid-cols-4 gap-3">
        {NIGERIAN_EXAMS_DATA.map((exam) => {
          const isSelected = selectedExam === exam.code;
          const isUserTarget = currentUser.targetExam === exam.code;

          return (
            <button
              key={exam.code}
              onClick={() => setSelectedExam(exam.code)}
              className={`p-4 rounded-2xl text-left border transition-all relative ${
                isSelected
                  ? 'bg-blue-50 dark:bg-blue-950/70 border-blue-600 shadow-md'
                  : 'bg-white dark:bg-slate-800 border-slate-200 dark:border-slate-700 hover:border-blue-300'
              }`}
            >
              {isUserTarget && (
                <span className="absolute top-3 right-3 text-[10px] font-bold px-1.5 py-0.2 rounded bg-emerald-500 text-white">
                  Active Goal
                </span>
              )}
              <div className="text-xl font-black text-slate-900 dark:text-white">{exam.code}</div>
              <div className="text-[11px] text-slate-500 dark:text-slate-400 line-clamp-1 mt-0.5">
                {exam.fullName}
              </div>
            </button>
          );
        })}
      </div>

      {/* Selected Examination Detailed Breakdown */}
      {activeExamData && (
        <div className="grid lg:grid-cols-12 gap-8">
          {/* Main Info (8 columns) */}
          <div className="lg:col-span-8 p-6 sm:p-8 rounded-3xl bg-white dark:bg-slate-800 border border-slate-200 dark:border-slate-700 shadow-xs space-y-6">
            <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-4 pb-4 border-b border-slate-100 dark:border-slate-700">
              <div>
                <span className="text-xs font-bold text-blue-600 dark:text-blue-400 uppercase tracking-wider">
                  Examination Profile
                </span>
                <h2 className="text-2xl font-extrabold text-slate-900 dark:text-white mt-1">
                  {activeExamData.fullName}
                </h2>
                <div className="text-xs text-slate-500 mt-1">
                  Target Candidate: {activeExamData.targetGroup}
                </div>
              </div>

              {currentUser.targetExam !== activeExamData.code ? (
                <button
                  onClick={() => handleSetTargetExam(activeExamData.code)}
                  className="px-4 py-2 rounded-xl bg-blue-600 text-white hover:bg-blue-700 text-xs font-semibold shadow-xs shrink-0"
                >
                  Set as My Primary Goal
                </button>
              ) : (
                <span className="px-3 py-1.5 rounded-xl bg-emerald-100 text-emerald-700 dark:bg-emerald-950 dark:text-emerald-300 text-xs font-bold flex items-center gap-1.5">
                  <CheckCircle2 className="w-4 h-4" />
                  <span>Your Current Target</span>
                </span>
              )}
            </div>

            <div className="space-y-4 text-xs sm:text-sm text-slate-700 dark:text-slate-300">
              <div>
                <h3 className="font-bold text-slate-900 dark:text-white mb-1">
                  Description & Scope:
                </h3>
                <p className="leading-relaxed text-slate-600 dark:text-slate-400">
                  {activeExamData.description}
                </p>
              </div>

              <div>
                <h3 className="font-bold text-slate-900 dark:text-white mb-1">
                  Exam Format & Structure:
                </h3>
                <p className="leading-relaxed text-slate-600 dark:text-slate-400 font-mono text-xs bg-slate-50 dark:bg-slate-900 p-3 rounded-xl border border-slate-200 dark:border-slate-700">
                  {activeExamData.examFormat}
                </p>
              </div>

              <div>
                <h3 className="font-bold text-slate-900 dark:text-white mb-2">
                  Key Subjects Covered on SmartTutor AI:
                </h3>
                <div className="flex flex-wrap gap-2">
                  {activeExamData.subjectsOffered.map((sub, i) => (
                    <span
                      key={i}
                      className="px-3 py-1.5 rounded-xl bg-slate-100 dark:bg-slate-700 text-slate-800 dark:text-slate-200 text-xs font-semibold"
                    >
                      {sub}
                    </span>
                  ))}
                </div>
              </div>

              <div className="p-4 rounded-2xl bg-blue-50 dark:bg-blue-950/60 border border-blue-200 dark:border-blue-900 text-xs text-blue-900 dark:text-blue-200 space-y-1">
                <div className="font-bold flex items-center gap-1.5">
                  <Flame className="w-4 h-4 text-amber-500" />
                  <span>SmartTutor Examiner Insider Strategy:</span>
                </div>
                <p>{activeExamData.keyTip}</p>
              </div>
            </div>

            <div className="pt-4 flex flex-wrap gap-3">
              <button
                onClick={() => selectTopicAndLaunch('math', 'math-algebra', 'quiz')}
                className="px-5 py-2.5 rounded-xl bg-blue-600 hover:bg-blue-700 text-white text-xs font-semibold shadow-xs"
              >
                Start Timed {activeExamData.code} Practice
              </button>
              <button
                onClick={() => selectTopicAndLaunch('math', 'math-algebra', 'practice')}
                className="px-4 py-2.5 rounded-xl bg-slate-100 dark:bg-slate-700 hover:bg-slate-200 text-slate-700 dark:text-white text-xs font-semibold"
              >
                Custom Practice Drills
              </button>
            </div>
          </div>

          {/* Side CBT Simulation Card (4 columns) */}
          <div className="lg:col-span-4 space-y-6">
            <div className="p-6 rounded-3xl bg-white dark:bg-slate-800 border border-slate-200 dark:border-slate-700 shadow-xs space-y-4">
              <div className="flex items-center gap-2">
                <div className="w-9 h-9 rounded-xl bg-purple-100 dark:bg-purple-950 text-purple-600 flex items-center justify-center font-bold text-xs">
                  CBT
                </div>
                <div>
                  <h3 className="text-sm font-bold text-slate-900 dark:text-white">
                    Simulated CBT Hall
                  </h3>
                  <p className="text-[11px] text-slate-400">Strict timed environment</p>
                </div>
              </div>

              <div className="space-y-2.5 text-xs text-slate-600 dark:text-slate-300">
                <div className="flex items-center gap-2">
                  <CheckCircle2 className="w-4 h-4 text-emerald-500 shrink-0" />
                  <span>Real countdown timer pacing</span>
                </div>
                <div className="flex items-center gap-2">
                  <CheckCircle2 className="w-4 h-4 text-emerald-500 shrink-0" />
                  <span>Auto-grading upon time expiry</span>
                </div>
                <div className="flex items-center gap-2">
                  <CheckCircle2 className="w-4 h-4 text-emerald-500 shrink-0" />
                  <span>Instant syllabus weak area tagger</span>
                </div>
              </div>

              <div className="pt-2">
                <button
                  onClick={() => selectTopicAndLaunch('math', 'math-algebra', 'quiz')}
                  className="w-full py-2.5 rounded-xl bg-purple-600 hover:bg-purple-700 text-white font-semibold text-xs shadow-md shadow-purple-500/20 flex items-center justify-center gap-2"
                >
                  <Clock className="w-3.5 h-3.5" />
                  <span>Launch CBT Exam Simulation</span>
                </button>
              </div>
            </div>

            {/* University 100-Level & Post-UTME Card */}
            <div className="p-6 rounded-3xl bg-white dark:bg-slate-800 border border-slate-200 dark:border-slate-700 shadow-xs space-y-3">
              <h3 className="text-sm font-bold text-slate-900 dark:text-white flex items-center gap-2">
                <BookOpen className="w-4 h-4 text-blue-600" />
                <span>University Entrance & 100-Level</span>
              </h3>
              <p className="text-xs text-slate-500 dark:text-slate-400">
                Transition smoothly to university calculus, general physics, organic chemistry, and academic writing.
              </p>
              <button
                onClick={() => {
                  setCurrentUser((prev) => ({ ...prev, level: 'University' }));
                  selectTopicAndLaunch('math', 'math-calculus', 'lesson');
                }}
                className="text-xs font-semibold text-blue-600 hover:text-blue-700 flex items-center gap-1"
              >
                <span>Switch to University Curriculum</span>
                <ArrowRight className="w-3.5 h-3.5" />
              </button>
            </div>
          </div>
        </div>
      )}
    </div>
  );
};
